"""Add passage_text to Question model.

Revision ID: 60bf17eb36cf
Revises: 1c046b398a3a
Create Date: 2025-07-15 11:41:12.133946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60bf17eb36cf'
down_revision = '1c046b398a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passage_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('passage_text')

    # ### end Alembic commands ###
