"""Add Stripe fields to User model.

Revision ID: fb351cef3c84
Revises: b7c09e5d018c
Create Date: 2025-07-16 12:26:20.962414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb351cef3c84'
down_revision = 'b7c09e5d018c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('is_subscribed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_subscribed')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
